Arbitrary compiler options
IonicaBizau/node-cobol pull request #40
Opened 2018-02-26 15:43 UTC by B14m3m3

Added a compiler options object that will be passed to the compiler, to enhance the thing in issue #39.

This should allow the user to specific whatever options there are in the cobc as required. I've added the free flag in the `Hello world` example to show the intended change.

As a small side change i also made was adding a callback to the Fs.unlink as it was giving deprecation errors :).  Currently the callback does nothing.

2018-02-26 16:10 UTC, IonicaBizau requested changes
Just a very small change in the example. Overall, it's good! :)

2018-02-26 16:10 UTC, IonicaBizau commented on examples/index.js
> +                   */}, {compileargs:{free:true}}, function (err, data) {
Can you please write this on multiple lines, so it won't be so condensed?

2018-02-26 16:10 UTC, IonicaBizau commented on lib/compile/index.js
> +            Object.assign(args, options.compileargs);
This looks good!

2018-02-26 17:14 UTC, B14m3m3 commented
Made the change to make the statement a bit more spacious :)

2018-02-28 15:19 UTC, B14m3m3 commented
@IonicaBizau I'm kinda new to adding things to open-source :) please notify me if another pull request or something has to be done. I should have fixed the example so that it's less condensed

2018-02-28 15:21 UTC, IonicaBizau approved these changes

2018-02-28 15:21 UTC, IonicaBizau commented
@B14m3m3 Sorry, I just missed your last commit. :see_no_evil: Do ping me in such cases. Merging right now. :ship:

2018-02-28 15:24 UTC, merged